# Generated by Django 5.0.6 on 2024-07-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('estado', models.CharField(choices=[('prestamo', 'Prestamo'), ('reservacion', 'Reservacion'), ('finalizado', 'Finalizado')], max_length=30)),
                ('total_pagar', models.FloatField()),
                ('total_pagado', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(max_length=9)),
                ('abogado', models.CharField(choices=[('abogado civil', 'Civil'), ('abogado penal', 'Penal'), ('abogado familiar', 'Familiar')], max_length=30)),
                ('detalle', models.CharField(max_length=190)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.cliente')),
            ],
        ),
    ]
