# Generated by Django 5.0.6 on 2024-07-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
